let number = [20, 30, 40, 50];
console.log(number);
console.log("Length " + number.length);
console.log("Three number of index " + number[3]);
number.push(60);
console.log("Push="+number);
number.pop();
console.log("Pop=" +number);
number.shift(10);
console.log("Shift="+number);
number.unshift(10);
console.log("Unshift="+number);
